pull_request_rules:
  - name: automatic merge for main when CI passes and 1 reviews and not WIP
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=build (2.13.6)
      - base=main
      - label!=work-in-progress
    actions:
      merge:
        method: merge
        priority: high
  - name: automatic merge for main when CI passes and author is steward
    conditions:
      - author=scala-steward
      - check-success=build (2.13.6)
      - base=main
    actions:
      merge:
        method: merge
